#language: csharp  
#sudo: required  
#dist: trusty  
#mono: none
#dotnet: 2.1.402
#before_script:
#  - dotnet restore
#script:  
#  - dotnet test ./ArgValidation.Tests -c Release -f netcoreapp2.1


language: csharp
dotnet: 2.1.402
sudo: false
mono: none

env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - CODECOV_TOKEN: fc123ca0-cc74-4ad7-9319-898e15bcbd69

before_script:
  - dotnet restore

script:
- dotnet build ArgValidation.sln -c Debug -f netstandard2.0
- dotnet test -c Debug --no-build ./ArgValidation.Tests/ArgValidation.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
- bash <(curl -s https://codecov.io/bash)
